version: "3.9"
services:
  anonymousnetwork:
    build: .
    container_name: LazarusVPN
    ports:
      - '9080:9080/tcp'
      - '51820:51820/udp'
    env_file:
      - .env
    privileged: true
    volumes:
      - /lib/modules:/lib/modules

