// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	model "github.com/TheLazarusNetwork/erebrus/model"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerServiceClient is the client API for ServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerServiceClient interface {
	GetServerInformation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*model.Response, error)
	GetServerConfiguraion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Config, error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*model.Status, error)
	UpdateServer(ctx context.Context, in *model.Server, opts ...grpc.CallOption) (*model.Response, error)
}

type serverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerServiceClient(cc grpc.ClientConnInterface) ServerServiceClient {
	return &serverServiceClient{cc}
}

func (c *serverServiceClient) GetServerInformation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*model.Response, error) {
	out := new(model.Response)
	err := c.cc.Invoke(ctx, "/server.ServerService/GetServerInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) GetServerConfiguraion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/server.ServerService/GetServerConfiguraion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*model.Status, error) {
	out := new(model.Status)
	err := c.cc.Invoke(ctx, "/server.ServerService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) UpdateServer(ctx context.Context, in *model.Server, opts ...grpc.CallOption) (*model.Response, error) {
	out := new(model.Response)
	err := c.cc.Invoke(ctx, "/server.ServerService/UpdateServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServiceServer is the server API for ServerService service.
// All implementations must embed UnimplementedServerServiceServer
// for forward compatibility
type ServerServiceServer interface {
	GetServerInformation(context.Context, *Empty) (*model.Response, error)
	GetServerConfiguraion(context.Context, *Empty) (*Config, error)
	GetStatus(context.Context, *Empty) (*model.Status, error)
	UpdateServer(context.Context, *model.Server) (*model.Response, error)
	mustEmbedUnimplementedServerServiceServer()
}

// UnimplementedServerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServerServiceServer struct {
}

func (UnimplementedServerServiceServer) GetServerInformation(context.Context, *Empty) (*model.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInformation not implemented")
}
func (UnimplementedServerServiceServer) GetServerConfiguraion(context.Context, *Empty) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerConfiguraion not implemented")
}
func (UnimplementedServerServiceServer) GetStatus(context.Context, *Empty) (*model.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedServerServiceServer) UpdateServer(context.Context, *model.Server) (*model.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServer not implemented")
}
func (UnimplementedServerServiceServer) mustEmbedUnimplementedServerServiceServer() {}

// UnsafeServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServiceServer will
// result in compilation errors.
type UnsafeServerServiceServer interface {
	mustEmbedUnimplementedServerServiceServer()
}

func RegisterServerServiceServer(s grpc.ServiceRegistrar, srv ServerServiceServer) {
	s.RegisterService(&ServerService_ServiceDesc, srv)
}

func _ServerService_GetServerInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).GetServerInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.ServerService/GetServerInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).GetServerInformation(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_GetServerConfiguraion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).GetServerConfiguraion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.ServerService/GetServerConfiguraion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).GetServerConfiguraion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.ServerService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_UpdateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).UpdateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.ServerService/UpdateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).UpdateServer(ctx, req.(*model.Server))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerService_ServiceDesc is the grpc.ServiceDesc for ServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.ServerService",
	HandlerType: (*ServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerInformation",
			Handler:    _ServerService_GetServerInformation_Handler,
		},
		{
			MethodName: "GetServerConfiguraion",
			Handler:    _ServerService_GetServerConfiguraion_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ServerService_GetStatus_Handler,
		},
		{
			MethodName: "UpdateServer",
			Handler:    _ServerService_UpdateServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/v1/server/server.proto",
}
